name: Publish Caddy docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Caddy version'
        required: true
        default: 2.7.5
        type: string

permissions: { }

jobs:
  publish-caddy-docker:
    name: Publish Caddy docker image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          docker-image: ghcr.io/aplinkosministerija/biip-caddy
          build-args: CADDY_VERSION=${{ inputs.version }}
          environment: ${{ inputs.version }}
          docker-context: docker/caddy
          push: true
